In [1]:
import numpy as np


In [3]:
# 0 dimensional array / Scaler
arr = np.array(42)
print (arr)

42


In [5]:
# 1 Dimensional Array
my_one_dim = np.array([1,2,3])
print (my_one_dim)

[1 2 3]


In [7]:
# 2 Dimensional Arrays
my_two_dim = np.array([[1,2,3],[4,5,6,]])
print (my_two_dim)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3 Dimensional Arrays
my_three_dim =  np.array([[[1,2,3,],[4,5,6,],[7,8,9,]]])
print (my_three_dim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
