In [1]:
import numpy as np


In [3]:
# 0 dimensional array / Scaler
arr = np.array(42)
print (arr)

42


In [5]:
# 1 Dimensional Array
my_one_dim = np.array([1,2,3])
print (my_one_dim)

[1 2 3]


In [7]:
# 2 Dimensional Arrays
my_two_dim = np.array([[1,2,3],[4,5,6,]])
print (my_two_dim)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3 Dimensional Arrays
my_three_dim =  np.array([[[1,2,3,],[4,5,6,]],[[1,2,3],[4,5,6,]]])
print (my_three_dim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
#initialising a numpy array
number_of_rows = 3
number_of_columns = 2
array_of_zeros = np.zeros((number_of_rows, number_of_columns))
print (array_of_zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
number_of_rows = 3
number_of_columns = 2
array_of_ones = np.ones((number_of_rows, number_of_columns))
print (array_of_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
arrays_of_5s = np.full((number_of_rows,number_of_columns),5)
print (5*(arrays_of_5s))

[[25 25]
 [25 25]
 [25 25]]


In [13]:
#Arrange
import numpy as np

start = 10
end = 26 #if we say 25, 25 will not be included
step = 3

evenly_step = np.arange(start, end, step)
evenly_step 

array([10, 13, 16, 19, 22, 25])

In [6]:
#Diagonal matrix
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#Random Integer Array
random_int_range = np.random.randint(0,10,(2,3)) #0-10 is the range and (2,3) are the rows and columns
random_int_range

array([[1, 0, 3],
       [2, 2, 3]])

In [12]:
random01 = np.random.random((2,3)) #random numbers in a 2 rows 3 columns array
random01

array([[0.49507037, 0.91513343, 0.51487099],
       [0.80242352, 0.77084243, 0.79029615]])

In [14]:
#Array is similar to list

list = [1,2,3]
arr = np.array

In [17]:
#Task 1 Find the odds in this array and replace them with their negative

array = np.array([0,2,4,5,3,7,8,9,5,1])
array [(array %2 == 1)] = -1 * array[(array%2 == 1)]
array 



array([ 0,  2,  4, -5, -3, -7,  8, -9, -5, -1])

In [36]:
#Numpy arithmetics
a = np.array([[1,2,5],[7,1,3]])
b = np.array([[4,6,9],[2,5,1,]])

add1 = a + b #this adds the arrays
add1

add2 =  np.add(a,b) #another way of adding arrays


sub1 = a - b


sub2 = np.subtract(a,b)
sub2

mul1 = a * b
mul1

mul2 = np.multiply(a,b)
mul2

div1 = a / b # You can use // for div 
div1

div2 = np.divide(a,b)
div2

exp =  np.exp(a)
sqroot =  np.sqrt(a)
sin = np.sin(a)
cos = np.cos(a)
log = np.log(a)

[[0 0 0]
 [3 0 3]]


array([[0.25      , 0.33333333, 0.55555556],
       [3.5       , 0.2       , 3.        ]])